### ISSUE TITLE
get_sin_steps - UnboundLocalError: local variable 'z' referenced before assignment

### ISSUE THREAD

**Issue by DonStroganotti** [Extraltodeus/advanced-loopback-for-sd-webui#1]
Seems like you are not correctly initializing the z variable when "Denoising strength start" isn't set to 0, which breaks the two sine variation options.

**Comment by Extraltodeus** [comment]
Actually it's the strength end that has to be used. If that slider is left at it's minimum value the the following options become useless.

**Comment by Extraltodeus** [comment]
Thanks, I fixed the function.
