### ISSUE TITLE
How to use multiple prompts

### ISSUE THREAD

**Issue by zchris07** [Extraltodeus/advanced-loopback-for-sd-webui#12]
Creator needs to address this, extension is unuseable:

https://www.reddit.com/r/StableDiffusion/comments/xzee5h/experimenting_with_advanced_loopback_for/

**Comment by Extraltodeus** [comment]
What do you mean unusable? Last time I checked it worked pretty fine 😂

**Comment by zchris07** [comment]
Yea if multiple people can't use it using your instructions maybe something's off. check out the post

**Comment by Extraltodeus** [comment]
I checked your link and did not see any mention of anything not working. Provide details.

**Comment by zchris07** [comment]
"The multiple prompts option will switch prompt after the "end" imager has been reached (referring to the input box) so 0-10 will switch prompts every 10 images."
What does this mean? Where is the input box? Where do you adjust the number of frames? Why is it producing 10 identical images instead of looping on the previous image?

**Comment by Extraltodeus** [comment]
>What does this mean?
prompts will switch every 10 images in this example

>Where is the input box
at the bottom, it is in the screenshots. That's the textbox.

>Why is it producing 10 identical images instead of looping on the previous image?
PEBCAK

It does not seem that my extension is having much actual issues so I close this ticket.

**Comment by zchris07** [comment]
you need to update your readme with your exact settings if you want people to actually use it. If I include 5 different prompts it just creates 5 frames with the first prompt. I just switched to loopback wave which actually worked and had legible instructions.
